export enum WeatherPreference {
  RAIN = 'RAIN',
  HIGH_TEMPERATURE = 'HIGH_TEMPERATURE',
  LOW_TEMPERATURE = 'LOW_TEMPERATURE',
  HIGH_WIND = 'HIGH_WIND',
  THUNDERSTORM = 'THUNDERSTORM',
  FOG = 'FOG',
  SNOW = 'SNOW',
  SEVERE_WEATHER = 'SEVERE_WEATHER',
  UV_INDEX = 'UV_INDEX',
  HUMIDITY = 'HUMIDITY',
}
